version: '3.5'
services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${PG_USER:-postgres}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-password}"
      POSTGRES_MULTIPLE_DATABASES: bc,kc
    volumes:
      - pg-data:/var/lib/backup/data
      - ./postgres:/docker-entrypoint-initdb.d

  keycloak:
    # https://ordina-jworks.github.io/security/2019/08/22/Securing-Web-Applications-With-Keycloak.htm
    image: jboss/keycloak
    container_name: keycloak
    #    entrypoint: /opt/jboss/tools/docker-entrypoint.sh -Dkeycloak.profile.feature.token_exchange=enabled
    expose:
      - 8080
    ports:
      - 9620:8080
    environment:
      # https://ultimatesecurity.pro/post/okta-oidc/
      KEYCLOAK_USER: "${KC_USER:-admin}"
      KEYCLOAK_PASSWORD: "${KC_PASSWORD:-beancounter}"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: kc
      DB_SCHEMA: public
      DB_USER: "${PG_USER:-postgres}"
      DB_PASSWORD: "${PG_PASSWORD:-password}"
      KEYCLOAK_IMPORT: /data/bc-dev-realm.json
    depends_on:
      - postgres
    volumes:
      - ./keycloak:/data

  data:
    image: monowai/bc-data
    container_name: data
    expose:
      - 9510
    # Ports should be published if you are running local:bc-view against this stack
    ports:
      - 9610:9510
    environment:
      SERVER_PORT: 9510
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bc
      SPRING_DATASOURCE_USERNAME: "${PG_USER:-postgres}"
      SPRING_DATASOURCE_PASSWORD: "${PG_PASSWORD:-password}"
      # https://docs.docker.com/compose/environment-variables/
      BEANCOUNTER_MARKETDATA_PROVIDER_WTD_KEY: ${WTD}
      AUTH_URI: "http://keycloak:8080/auth"
      AUTH_REALM: "bc-dev"
    links:
      - postgres

  position:
    image: monowai/bc-position
    container_name: position
    expose:
      - 9500
    # Publish this if you are running local:bc-view against docker services
    ports:
      - 9600:9500

    environment:
      SERVER_PORT: 9500
      MARKETDATA_URL: "http://data:9510/api"
      MANAGEMENT_SERVER_PORT: 9621
      AUTH_URI: "http://keycloak:8080/auth"
      AUTH_REALM: "bc-dev"
    depends_on:
      - data

  app:
    image: monowai/bc-app
    ports:
      - 4000:3000

    container_name: app
    environment:
      SVC_POSITION: "http://position:9500"
      SVC_DATA: "http://data:9510"
      RAZZLE_PUBLIC_DIR: "http://localhost:4000"
      KC_CLIENT: bc-demo
    depends_on:
      - position
      - data

volumes:
  pg-data: