version: '3.5'
services:
  shell:
    # docker-compose -f shell.yml run --rm shell
    image: monowai/bc-shell:12184
    container_name: shell
    ports:
      - "9690:9690"
    env_file:
      - .env
    environment:
      MARKETDATA_URL: "http://host.docker.internal:9610"
      MARKETDATA_ACTUATOR: "http://host.docker.internal:9611"
      API_PORT: 9690
      BEANCOUNTER_TOPICS_TRN_CSV: bc-trn-csv-demo


