version: '3.5'
services:
  shell:
    # docker-compose -f shell.yml run --rm shell
    image: monowai/bc-shell:2237
    container_name: shell
    ports:
      - "9690:9690"
    env_file:
      - .env
    environment:
      #MARKETDATA_URL: "http://host.docker.internal:9610"
      #MARKETDATA_ACTUATOR: "http://host.docker.internal:9611"
      # reaches using internal network and ports
      # https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
      MARKETDATA_URL: "http://data:9510"
      MARKETDATA_ACTUATOR: "http://data:9511"
      API_PORT: 9690
      BEANCOUNTER_TOPICS_TRN_CSV: bc-trn-csv-demo
    networks:
      - bcdemo

networks:
  bcdemo:
    name: bcdemo
